apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-server.fullname" . }}
  namespace: {{ .Values.service.namespace }}
  labels:
    name: {{ include "discovery-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP

  selector:
    name: {{ include "discovery-server.fullname" . }}
    deploymentType: {{ .Values.deploymentType }}
